@startuml
title "Simulink to COSMOS\n(Intermediate Communication)"

left to right direction

skinparam BackgroundColor transparent
skinparam componentStyle uml2

frame CommunicationWrapper {
    frame Simulink {
        component VehicleModel 
        component MissionConfiguration
        component Environment
        component Visualization 
    }
    component MessageBuilder
    component DataPublisher
}

frame COSMOS {
    component DataReceipient
    component TelemetryProcessor
    node VisualizationTools {
        component TelemetryViewer
        component PacketViewer
        component TelemetryGrapher
        component DataViewer
    }
}

'Simulink
[VehicleModel] --> [Environment]
[Environment] --> [VehicleModel]
[MissionConfiguration] --> [VehicleModel]
[VehicleModel] --> [Visualization]

' Communication
[VehicleModel] --> [MessageBuilder] : Telemetry
[MessageBuilder] --> [DataPublisher] : Packets
[DataPublisher] --> [DataReceipient] : UDP

' COSMOS
[DataReceipient] --> [TelemetryProcessor] 
[TelemetryProcessor] --> [TelemetryViewer]
[TelemetryProcessor] --> [PacketViewer]
[TelemetryProcessor] --> [TelemetryGrapher]
[TelemetryProcessor] --> [DataViewer]

@enduml
